# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NexPloitRerunScan@3
  inputs:
    apiToken: '$(APITOKENBRIGHT)'
    hostname: 'app.brightsec.com'
    scanId: 'uCU4f96xkjtn95aGjvmiae'
    name: 'Azure DevOps Pipeline Scan'